/**
 * Run every benchmark suite (or a subset) and write:
 *   benchmark-results/<suite>.json   machine-readable per suite
 *   benchmark-results/REPORT.md      human-readable summary of all suites
 *
 * Usage:
 *   npx tsx --expose-gc tests/performance/run-all.ts            # all suites
 *   npx tsx --expose-gc tests/performance/run-all.ts workspace   # by name fragment
 *   npx tsx --expose-gc tests/performance/run-all.ts --report    # only rebuild REPORT.md
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  printSuite,
  readAllSuiteResults,
  renderMeasurementsTable,
  resultsDir,
  writeSuiteResult,
  type BenchmarkSuiteResult,
} from './benchmark-utils.ts';
import { runWorkspaceAnalysisBenchmark } from './workspace-analysis.bench.ts';
import { runLazyVsEagerBenchmark } from './lazy-vs-eager.bench.ts';
import { runRouteAnalysisBenchmark } from './route-analysis.bench.ts';
import { runCallChainBenchmark } from './call-chain.bench.ts';
import { runTraceOverlayBenchmark } from './trace-overlay.bench.ts';
import { runRuntimeCollectorBenchmark } from './runtime-collector.bench.ts';
import { runInstrumentationOverheadBenchmark } from './instrumentation-overhead.bench.ts';
import { runGraphProjectionBenchmark } from './graph-projection.bench.ts';
import { runDocumentSizeBenchmark } from './document-size.bench.ts';

const SUITES: Array<{ name: string; run: () => Promise<BenchmarkSuiteResult> }> = [
  { name: 'workspace-analysis', run: runWorkspaceAnalysisBenchmark },
  { name: 'lazy-vs-eager', run: runLazyVsEagerBenchmark },
  { name: 'route-analysis', run: runRouteAnalysisBenchmark },
  { name: 'call-chain', run: runCallChainBenchmark },
  { name: 'trace-overlay', run: runTraceOverlayBenchmark },
  { name: 'runtime-collector', run: runRuntimeCollectorBenchmark },
  { name: 'instrumentation-overhead', run: runInstrumentationOverheadBenchmark },
  { name: 'graph-projection', run: runGraphProjectionBenchmark },
  { name: 'document-size', run: runDocumentSizeBenchmark },
];

/** Columns shown in REPORT.md per suite (others remain in the JSON). */
const REPORT_COLUMNS: Record<string, string[]> = {
  'workspace-analysis': ['files', 'nodes', 'edges', 'routes', 'traces', 'scanMs', 'parseMs', 'routeMs', 'callChainMs'],
  'lazy-vs-eager': ['files', 'rootNodes', 'nodes', 'edges', 'routes'],
  'route-analysis': ['style', 'files', 'routes', 'medianMs5', 'usPerRoute'],
  'call-chain': ['routes', 'nodes', 'edges', 'deepest', 'cycleEdges', 'truncated', 'calleeCacheHitPct'],
  'trace-overlay': ['spans', 'overlayNodes', 'overlayEdges', 'graphNodes', 'graphEdges', 'jsonMb', 'usPerSpan'],
  'runtime-collector': ['events', 'issues', 'completed', 'active', 'evicted', 'droppedSpans', 'lateEvents', 'usPerEvent'],
  'instrumentation-overhead': ['p50Ms', 'p95Ms', 'p99Ms', 'rps', 'cpuMsPerReq', 'meanDeltaMs', 'meanDeltaPct', 'p95DeltaMs', 'rpsDeltaPct', 'cpuDeltaUsPerReq'],
  'graph-projection': ['nodes', 'edges', 'engine', 'medianMs5'],
  'document-size': ['files', 'modules', 'dependencies', 'docKb', 'docLines', 'agentContextKb', 'bytesPerFile'],
};

function renderReport(results: BenchmarkSuiteResult[]): string {
  const lines: string[] = [];
  lines.push('# CodeMap Benchmark Report', '');
  lines.push(
    '_Generated by `npm run benchmark`. Numbers are single-machine measurements on synthetic fixtures; they describe scaling behaviour, not universal performance claims._',
    '',
  );
  const env = results[0]?.environment;
  if (env) {
    lines.push('## Environment', '');
    lines.push(`- Node ${env.node}, ${env.platform} ${env.release} (${env.arch})`);
    lines.push(`- CPU: ${env.cpuModel} × ${env.cpuCount}`);
    lines.push(`- Memory: ${env.totalMemoryGb} GB`);
    lines.push(`- GC exposed for heap deltas: ${env.gcExposed ? 'yes' : 'no (heap Δ includes uncollected garbage)'}`);
    lines.push(`- Generated: ${env.timestamp}`);
    lines.push('');
  }
  for (const result of results) {
    lines.push(`## ${result.suite}`, '');
    lines.push(result.description, '');
    const columns = REPORT_COLUMNS[result.suite] ?? Object.keys(result.measurements[0]?.metrics ?? {});
    const includeMemory = result.suite !== 'instrumentation-overhead';
    lines.push(renderMeasurementsTable(result.measurements, columns, { includeMemory }), '');
    if (result.suite === 'instrumentation-overhead') {
      lines.push('_Time (ms) column is mean request latency; `difference` rows show instrumented − baseline._', '');
    }
    for (const note of result.notes) {
      lines.push(`- ${note}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

export function writeReport(): string {
  const results = readAllSuiteResults();
  const file = join(resultsDir(), 'REPORT.md');
  writeFileSync(file, renderReport(results), 'utf8');
  return file;
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const reportOnly = args.includes('--report');
  const filters = args.filter((a) => !a.startsWith('--'));

  if (!reportOnly) {
    const selected = SUITES.filter(
      (s) => filters.length === 0 || filters.some((f) => s.name.includes(f)),
    );
    if (selected.length === 0) {
      console.error(`No suites match ${filters.join(', ')}. Available: ${SUITES.map((s) => s.name).join(', ')}`);
      process.exitCode = 1;
      return;
    }
    for (const suite of selected) {
      const started = Date.now();
      try {
        const result = await suite.run();
        printSuite(result);
        writeSuiteResult(result);
        console.log(`  (${suite.name} finished in ${((Date.now() - started) / 1000).toFixed(1)}s)`);
      } catch (err) {
        console.error(`suite ${suite.name} failed:`, err);
        process.exitCode = 1;
      }
    }
  }

  const report = writeReport();
  console.log(`\nreport: ${report}`);
}

void main();
